using Pkg;
Pkg.update();
Pkg.add("IJulia");
Pkg.add("Gadfly");
Pkg.add("RDatasets");
Pkg.add("Distances");
Pkg.add("StatsBase");
Pkg.add("Hadamard");
Pkg.add("JLD");
Pkg.add("StatsBase");
Pkg.add("Statistics");
Pkg.add("Embeddings");
Pkg.add("DataFrames");
Pkg.add("GLM");
Pkg.add("LsqFit");
Pkg.add("Combinatorics");
Pkg.add("Cairo");
Pkg.precompile();
