#!/usr/bin/env bash

DOCKERFILE_ROOT_DIR=/home/ubuntu/docker-jupyter/images
REGISTRY_NAME=quay.io/prete/docker-jupyter

for TAG_NAME in "base" "julia" "r-base" "r-full"
#     	"teichlab"
do
    echo "=========================================" >> $DOCKERFILE_ROOT_DIR/../build_log.txt
    cd $DOCKERFILE_ROOT_DIR/$TAG_NAME
    echo "🐳 Building $TAG_NAME" >> $DOCKERFILE_ROOT_DIR/../build_log.txt
    docker build -t "$REGISTRY_NAME:$TAG_NAME" .
    RESULT=$?
    if [ $RESULT -eq 0 ]; then
      echo "✅ $TAG_NAME build successfully!"  >> $DOCKERFILE_ROOT_DIR/../build_log.txt
    else
      echo "⚠️  $TAG_NAME build failed!"  >> $DOCKERFILE_ROOT_DIR/../build_log.txt
    fi
done
