#!/usr/bin/env bash

REGISTRY_NAME=quay.io/prete/docker-jupyter

for TAG_NAME in "base" "r-4.0.3" "teichlab"
do
    IMAGE=$REGISTRY_NAME:$TAG_NAM
    echo "🐳 Pushing $IMAGE"
    docker push IMAGE 2> $TAG_NAME.log.txt
    RESULT=$?
    if [ $RESULT -eq 0 ]; then
      echo "✅ push $IMAGE success!"
    else
      echo "⚠️  push $IMAGE failed!"
    fi
done

