name: base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python = 3.8
  - pip >= 20.2.4
  - numpy >= 1.19.2
  - pandas >= 1.1.4
  - cython >= 0.29.21
  - python-igraph >= 0.8.3
  - louvain >= 0.6.1
  - leidenalg >= 0.8.0
  - gpy >= v1.9.9 
  - scanpy >= 1.5.1
  - scikit-learn >= 0.23.1
  - jupyter >= 1.0.0
  - jupyterlab >= 2.2.8
  - matplotlib >= 3.2.1
  - snakemake >= 5.26.1
  - ipykernel >= 5.3.4
  - cmake >= 3.18.4
  - sccaf >= 0.0.10
  - pytest >= 6.1.2
  - plotly >= 4.12.0
  - h5py < 3.0.0
#  - ggplot >= 0.11.5
  - scvi-tools >= 0.7.1
  - bbknn >= 1.3.9
  - pip:
    - velocyto
    - fitsne
    - spatialde
    - polo
    - rpy2
    - scvelo
    - wot
    - cellphonedb
    - pyscenic
    - scirpy
    - palantir

